[package]
name = "subhub-app"
version.workspace = true
edition.workspace = true
default-run = "subhub-app"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
subhub-core = { path = "../core" }
subhub-server = { path = "../server" }
tokio = { version = "1", features = ["full"] }
